services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - APP_TITLE=${APP_TITLE}
      - APP_VERSION=${APP_VERSION}
      - APP_DESCRIPTION=${APP_DESCRIPTION}
      - HOST=0.0.0.0
      - PORT=8000
    restart: unless-stopped
