name: Build, Push, and Deploy Container

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # Checkout repository
      - name: Checkout Repository
        uses: actions/checkout@v4

      # Log in to Azure Container Registry
      - name: Azure Docker Login
        uses: azure/docker-login@v1
        with:
          login-server: ${{ secrets.ACR_LOGIN_SERVER }}
          username: ${{ secrets.ACR_USERNAME }}
          password: ${{ secrets.ACR_PASSWORD }}

      # Build your Docker image and tag it with the commit SHA
      - name: Build Docker Image
        run: |
          docker build -t ${{ secrets.ACR_LOGIN_SERVER }}/prom-chat:${{ github.sha }} .

      # Push the image to your Azure Container Registry
      - name: Push Docker Image to ACR
        run: |
          docker push ${{ secrets.ACR_LOGIN_SERVER }}/prom-chat:${{ github.sha }}

      # Log in to Azure using your service principal credentials
      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      # Deploy the container image to your Azure Web App
      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: "promtiot-chatbot-app"
          images: "${{ secrets.ACR_LOGIN_SERVER }}/prom-chat:${{ github.sha }}"
          configuration-string: |
            WEBSITES_PORT=8000
            OPENAI_API_KEY=${{ secrets.OPENAI_API_KEY }}
